set_property SRC_FILE_INFO {cfile:C:/Users/ethan/Documents/temp/thing/cores/managed_ip_project/managed_ip_project.runs/mig_7series_0_synth_1/mig_7series_0/mig_7series_0_in_context.xdc rfile:../../../../../../../temp/thing/cores/managed_ip_project/managed_ip_project.runs/mig_7series_0_synth_1/mig_7series_0/mig_7series_0_in_context.xdc id:1 order:EARLY scoped_inst:mig} [current_design]
set_property SRC_FILE_INFO {cfile:c:/Users/ethan/Documents/temp/thing/cores/mig_7series_0/mig_7series_0/mig_7series_0_in_context.xdc rfile:../../../../../../../temp/thing/cores/mig_7series_0/mig_7series_0/mig_7series_0_in_context.xdc id:2 order:EARLY scoped_inst:mig} [current_design]
set_property SRC_FILE_INFO {cfile:{c:/Users/ethan/Documents/GitHub/Ray-Tracing/FPGA Programs/RayTraceDemo/RayTraceDemo.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0/clk_wiz_0_in_context.xdc} rfile:../../../RayTraceDemo.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0/clk_wiz_0_in_context.xdc id:3 order:EARLY scoped_inst:wiz} [current_design]
set_property SRC_FILE_INFO {cfile:{C:/Users/ethan/Documents/GitHub/Ray-Tracing/FPGA Programs/RayTraceDemo/RayTraceDemo.srcs/constrs_1/new/topCons.xdc} rfile:../../../RayTraceDemo.srcs/constrs_1/new/topCons.xdc id:4} [current_design]
current_instance mig
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 12.308 [get_ports {}]
set_property src_info {type:SCOPED_XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 12.308 [get_ports {}]
current_instance
current_instance wiz
set_property src_info {type:SCOPED_XDC file:3 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 [get_ports -no_traverse {}]
set_property src_info {type:SCOPED_XDC file:3 line:4 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -source [get_ports clk_in1] -edges {1 2 3} -edge_shift {0.000 0.000 0.000} [get_ports {}]
set_property src_info {type:SCOPED_XDC file:3 line:6 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -source [get_ports clk_in1] -edges {1 2 3} -edge_shift {0.000 -2.500 -5.000} [get_ports {}]
current_instance
set_property src_info {type:XDC file:4 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P6 [get_ports button]
set_property src_info {type:XDC file:4 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K13 [get_ports led1]
set_property src_info {type:XDC file:4 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K12 [get_ports led2]
set_property src_info {type:XDC file:4 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L14 [get_ports led3]
set_property src_info {type:XDC file:4 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N14 [get_ports clk]
set_property src_info {type:XDC file:4 line:27 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name mig/u_mig_7series_0_mig/u_ddr3_infrastructure/mmcm_clk -waveform {0.000 5.000} [get_pins mig/u_mig_7series_0_mig/u_ddr3_infrastructure/plle2_i/CLKIN1]
