# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/ethan/Documents/GitHub/Ray-Tracing/FPGA HDL/Ram/constraint/alchitry.xdc

# XDC: C:/Program Files/Alchitry/Alchitry Labs/library/components/au.xdc

# IP: ip/mig_7series_0/mig_7series_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mig_7series_0 || ORIG_REF_NAME==mig_7series_0} -quiet] -quiet
